# Strings that are used many times in the code
REGISTRY = 'registry'
PACKAGE = 'package'
LICENSE = 'license'
VERSION = 'version'
URL = 'url'
ERROR = 'error'
PRODUCTION = 'production'
DEVELOPMENT = 'development'
OWNER = 'owner'
REASON = 'reason'
MULTI_LICENSE_SELECTION = 'multi-license-selection'
ADD_PACKAGE_NAME = 'add-packages'
OVERWRITES_NAME = 'overwrites'
MULTI_LICENSE_SELECTION_NAME = 'multi-license-selection'
ADDITIONAL_INFO_NAME = 'additional-info'
